/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class shendi_test_wlan_WlanUtil */

#ifndef _Included_shendi_test_wlan_WlanUtil
#define _Included_shendi_test_wlan_WlanUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     shendi_test_wlan_WlanUtil
 * Method:    openHandle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_shendi_test_wlan_WlanUtil_openHandle
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     shendi_test_wlan_WlanUtil
 * Method:    closeHandle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_shendi_test_wlan_WlanUtil_closeHandle
  (JNIEnv *, jobject);

/*
 * Class:     shendi_test_wlan_WlanUtil
 * Method:    getWlanEnumInterfaces
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_shendi_test_wlan_WlanUtil_getWlanEnumInterfaces
(JNIEnv *, jobject, jobject);

/*
 * Class:     shendi_test_wlan_WlanUtil
 * Method:    disconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_shendi_test_wlan_WlanUtil_disconnect
(JNIEnv *, jobject, jint);

/*
 * Class:     shendi_test_wlan_WlanUtil
 * Method:    connect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_shendi_test_wlan_WlanUtil_connect
(JNIEnv *, jobject, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
